#!/bin/bash

#change these parameters for each event 
export file="CMTSOLUTION_201810131110A_GCMT"
export filtering="fortran_format_18_40_18_60_45_100" #from the database event folder 
export duration="6.24" #twice the half-duration/sqrt(3)
export strike1="99" #from GCMT catalogue 
export dip1="42"
export strike2="352"
export dip2="74"
export lat="52.71" 
export lon="153.43" 
export path="" #location of tempseis

################################################################################

rm Inversion/NA/data/rfi_files/OBS/*
rm Inversion/NA/src/rfi_subs/point_source/*
cd $path/TEMPSEIS_PACKAGE/Inversion/NA/src/rfi_subs/
rm ./kernels/*
cd $path/TEMPSEIS_PACKAGE/

cp database/$file/$filtering/point_source/* Inversion/NA/src/rfi_subs/point_source/
cp database/$file/$filtering/observed_data/* Inversion/NA/data/rfi_files/OBS/

for d  in database/$file/$filtering/derivatives/*
do
cp $d  Inversion/NA/src/rfi_subs/kernels/
done

###############################################################################################################################################################
cd $path/TEMPSEIS_PACKAGE/Inversion/Preparation

python create_station_file_azimut.py 

cd $path/TEMPSEIS_PACKAGE/Inversion

cp $path/TEMPSEIS_PACKAGE/Inversion/Preparation/rfi.in $path/TEMPSEIS_PACKAGE/Inversion/NA/data/rfi_files/

###############################################################################################################################################################

cd $path/TEMPSEIS_PACKAGE/Inversion/NA/data

./jobaspect2_confined

