#!/bin/bash

#change these parameters for each event 
export file="CMTSOLUTION_201810131110A_GCMT"
export filtering="fortran_format_18_40_18_60_45_100" #from the database event folder 
export duration="6.24" #twice the half-duration/sqrt(3)
export strike1="99" #from GCMT catalogue 
export dip1="42"
export strike2="352"
export dip2="74"
export lat="52.71" 
export lon="153.43" 
export path="" #location of tempseis

################################################################################

OBS_DATA_DIR=Inversion/NA/data/rfi_files/OBS  # these will need to change
POINT_SOURCE_DIR=Inversion/NA/src/rfi_subs/point_source
KERNELS_DIR=Inversion/NA/src/rfi_subs/kernels

rm ${OBS_DATA_DIR}/*
rm ${POINT_SOURCE_DIR}/*
rm ${KERNELS_DIR}/*

cp database/$file/$filtering/observed_data/* ${OBS_DATA_DIR}/
cp database/$file/$filtering/point_source/* ${POINT_SOURCE_DIR}/
cp database/$file/$filtering/derivatives/* ${KERNELS_DIR}/

python pytempseis/create_station_file_azimut.py $file $filtering ${OBS_DATA_DIR}

cp rfi.in $path/TEMPSEIS_PACKAGE/Inversion/NA/data/rfi_files/

###############################################################################################################################################################

cd $path/TEMPSEIS_PACKAGE/Inversion/NA/data

./jobaspect2_confined

