#!/bin/bash

#looping over different aspect ratios (Amin/Amax) for one fault plane 
for b  in 28.86751346 14.4337567 9.62250449 7.21687836 5.77350269 4.81125205 4.12393049 3.60843918 3.207501495 2.88675135
do
a=$(bc <<< "scale=3;5/($b*1.732050807568877)")
cat > $path/TEMPSEIS_PACKAGE/Inversion/NA/data/rfi_files/NA_MDL/rfi_param << *
6 0
0.0     0.0   0    0.0   0.0  0   0.00  0.00 0  spatial_centroid: |rc| (km), rc ang (a-clockwisetostrike).
-10  10  0    0.0   0.0  0   0.00  0.00 0     delta_time_centroid(s)
0.0   $duration  0    0.0   0.0  0   0.00  0.00 0     duration(s)
0.0    10.0    0  -90.0  90.0  0   0.00  0.00 0     velocity: abs_value, beta (degrees)
$b  100.0 0  $a    $a   0  -90.00  90.00 0    char. dimensions: Amax (km), Amin/Amax, phi
$strike1.   $strike1.    0 $dip1.  $dip1.  0   0.00  0.00 0     strike, dip (degrees)

*
cd $path/TEMPSEIS_PACKAGE
./run_inversion

cd -
#looping over different aspect ratios (Amin/Amax) for the other fault plane 
for b in 28.86751346 14.4337567 9.62250449 7.21687836 5.77350269 4.81125205 4.12393049 3.60843918 3.207501495 2.88675135
do
a=$(bc <<< "scale=3;5/($b*1.732050807568877)")
cat > $path/TEMPSEIS_PACKAGE/Inversion/NA/data/rfi_files/NA_MDL/rfi_param << *
6 0
0.0     0.0   0    0.0   0.0  0   0.00  0.00 0  spatial_centroid: |rc| (km), rc ang (a-clockwisetostrike).
-10  10  0    0.0   0.0  0   0.00  0.00 0     delta_time_centroid(s)
0   $duration   0    0.0   0.0  0   0.00  0.00 0     duration(s)
0.0    10.0    0  -90.0  90.0  0   0.00  0.00 0     velocity: abs_value, beta (degrees)
$b  100.0   0    $a  $a  0  -90.00  90.00 0    char. dimensions: Amax (km), Amin/Amax, phi
$strike2.   $strike2.    0 $dip2.  $dip2.  0   0.00  0.00 0     strike, dip (degrees)

*
cd $path/TEMPSEIS_PACKAGE
./run_inversion

done 
